apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhn-support-csears-tenant/devfile-sample-python-basic/devfile-sample-python-basic@sha256:d7769b2a3c791bce021df24fbd3690ff3b113da058c93001eb0fcec045b1cdc3
        name: my-python
        resources: {}
status: {}
